apiVersion: certsmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: mydomain-com-tls
spec:
  secretName: mydomain-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: mydomain.com
  dnsNames:
    - mydomain.com
    - www.mydomain.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - mydomain.com
          - www.mydomain.com